import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import Image from 'next/image'
import iconpic from '../../public/Vk-vN6Pv_400x400.jpg'
import Head from 'next/head'

export const metadata: Metadata = {
    title: 'ocepowerhouse',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                <a href='/about/mumbai' id="Mumbai">Mumbai Monkeys</a>
                <a href='/about/filler' id="Shroud">Filler</a>
                </div>
                {children}
            </body>
        </html>
    )
}